# Schema for configuration files of the Entity browser module.

entity_browser.browser.*:
  type: config_entity
  label: 'Entity browser'
  mapping:
    name:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    display:
      type: string
      label: 'Display plugin ID'
    display_configuration:
      type: entity_browser.browser.display.[%display]
    selection_display:
      type: string
      label: 'Selection display plugin ID'
    selection_display_configuration:
      type: entity_browser.browser.selection_display.[%selection_display]
    widget_selector:
      type: string
      label: 'Widget selector plugin ID'
    widget_selector_configuration:
      type: entity_browser.browser.widget_selector.[%widget_selector]
    widgets:
      type: sequence
      label: 'Widgets'
      sequence:
        - type: mapping
          mapping:
            id:
              type: string
            uuid:
              type: string
            label:
              type: string
            weight:
              type: integer
            settings:
              type: entity_browser.browser.widget.[%parent.id]
